name: minimart
description: "An eCommerce Preview App"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^10.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.10
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
