name: minimart
description: "An eCommerce Preview App"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  intl_utils: ^2.8.10
  provider: ^6.1.5

dev_dependencies:
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lean_builder: ^0.1.0-alpha.12

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/minimart_data.json
  fonts:
    - family: MinimartIcons
      fonts:
        - asset: assets/fonts/MinimartIcons.ttf
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Thin.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Bold.ttf
          weight: 700
          style: normal
flutter_intl:
  enabled: true
