/// Flutter icons MinimartIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MinimartIcons
///      fonts:
///       - asset: fonts/MinimartIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class MinimartIcons {
  MinimartIcons._();

  static const _kFontFam = 'MinimartIcons';
  static const String? _kFontPkg = null;

  static const IconData check_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outlined = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_outlined = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_outlined = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_outlined = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_outlined = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fav_filled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_outlined = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fav_outlined = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_outlined = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
